ssh_opts:
    - '-oConnectTimeout=2'
    - '-oStrictHostKeyChecking=no'
    - '-oUserKnownHostsFile=/dev/null'
    - '-oLogLevel=error'
    - '-lroot'
    - '-oBatchMode=yes'
env_vars:
    - 'OPENRC=/root/openrc'
    - 'IPTABLES_STR="iptables -nvL"'
# fuel_ip:  '127.0.0.1'
# fuel_user: 'admin'
# fuel_pass: 'admin'
rqdir: './rq'
rqfile: './rq.yaml'
soft_filter:
    status:  ['ready']
    online: True
    # no_id: [0] # skip Fuel
    # no_roles: ['fuel'] # another way to skip Fuel
timeout: 15
compress_timeout: 3600
logs:
    path: '/var/log'
    exclude: '[-_]\d{8}$|atop[-_]|\.gz$'
# by_roles:
#     compute:
#         logs:
#             path: '/var/log'
#             include: 'compute'
#     ceph-osd:
#         logs:
#             path: '/var/log'
#             include: 'ceph'
#             start: '2016-05-05'
# by_id:
#     1:
#         env_vars:
#             - 'OPENRC=/root/openrc'
#             - 'IPTABLES_STR="iptables -S"'
#         logs:
#             path: '/var/log'
#             start: '2016-05-08 22:00:01'
#         cmds:
#             - 'df-m'
