ssh:
    opts: -oConnectTimeout=2 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error -lroot -oBatchMode=yes
    vars: OPENRC=/root/openrc IPTABLES_STR="iptables -nvL"
fuelip:  127.0.0.1
rqdir:   ./rq
logdir:  ./logs
out-dir: ../timmy-ng/info
timeout: 15
find:
    template: -name '*.log'
